IF (OPENVOLUMEMESH_INCLUDE_DIR)
  SET(OPENVOLUMEMESH_FIND_QUIETLY TRUE)
ENDIF (OPENVOLUMEMESH_INCLUDE_DIR)

FIND_PATH(OPENVOLUMEMESH_INCLUDE_DIR OpenVolumeMesh/Mesh/TetrahedralMesh.hh
	  PATHS "${CMAKE_SOURCE_DIR}/extern/OpenVolumeMesh/src"
           "${CMAKE_SOURCE_DIR}/../OpenVolumeMesh/src"
           "${CMAKE_CURRENT_SOURCE_DIR}/extern/OpenVolumeMesh/src"
           "${CMAKE_CURRENT_SOURCE_DIR}/../OpenVolumeMesh/src"
            /usr/include
            /usr/local/OpenVolumeMesh/include
            )

IF (OPENVOLUMEMESH_INCLUDE_DIR )
   SET(OPENVOLUMEMESH_FOUND TRUE)
   IF (WIN32)
      IF(EXISTS "${OPENVOLUMEMESH_INCLUDE_DIR}/../lib")
         SET(OPENVOLUMEMESH_LIBRARY_DIR "${OPENVOLUMEMESH_INCLUDE_DIR}/../lib")
      ENDIF()
   ELSE (WIN32)
      IF(EXISTS "${OPENVOLUMEMESH_INCLUDE_DIR}/../lib/OpenVolumeMesh")
            SET(OPENVOLUMEMESH_LIBRARY_DIR "${OPENVOLUMEMESH_INCLUDE_DIR}/../lib/OpenVolumeMesh")
      ENDIF()
   ENDIF (WIN32)
   SET(OPENVOLUMEMESH_LIBRARY "OpenVolumeMesh")
ELSE (OPENVOLUMEMESH_INCLUDE_DIR)
   SET(OPENVOLUMEMESH_FOUND FALSE )
ENDIF (OPENVOLUMEMESH_INCLUDE_DIR )
